Schools.AspMvc/Controllers/CityController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Localization;
using Newtonsoft.Json;
using Schools.MVC.Models;
using System.Security.Claims;
using System.Text;

namespace Schools.MVC.Controllers
{
    public class CityController : Controller
    {
        private readonly HttpClient _client;
        private readonly IConfiguration _config;

        public CityController(HttpClient client, IStringLocalizer<CityController> localizer, IConfiguration config)
        {
            var baseAddressFromSettings = config.GetSection("AppSettings:BaseAddress").Value;

            if (string.IsNullOrWhiteSpace(baseAddressFromSettings))
            {
                throw new ArgumentNullException("baseAddressFromSettings");
            }

            _client = new HttpClient();
            _client.BaseAddress = new Uri(uriString: baseAddressFromSettings);
            _config = config;
        }

        [HttpGet]
        //[Authorize(Roles = "Claim_Role")]
        public IActionResult Index()
        {


            var user = User;

            var cityList = new List<CityViewModel>();

            //call to web api micro-service endpoint
            HttpResponseMessage response = _client.GetAsync(_client.BaseAddress + "/city/GetAll").Result;

            if (response.IsSuccessStatusCode)
            {
                string data = response.Content.ReadAsStringAsync().Result;
                cityList = JsonConvert.DeserializeObject<List<CityViewModel>>(data);
            }

            return View(cityList);
        }

        [HttpGet]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public IActionResult Create(CityViewModel model)
        {
            try
            {
                string data = JsonConvert.SerializeObject(model);
                StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
                HttpResponseMessage response = _client.PostAsync(_client.BaseAddress + "/City", content).Result;

                if (response.IsSuccessStatusCode)
                {
                    TempData["successMessage"] = "City created.";
                    return RedirectToAction("Index");
                }

            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
            return View();
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            try
            {
                CityViewModel cityViewModel = null;

                var response = _client.GetAsync(_client.BaseAddress + "/City/GetById/" + id).Result;

                if (response.IsSuccessStatusCode)
                {
                    string data = response.Content.ReadAsStringAsync().Result;
                    cityViewModel = JsonConvert.DeserializeObject<CityViewModel>(data);
                }
                else
                {
                    TempData["errorMessage"] = "Some error occured.";
                }
                return View(cityViewModel);

            }
            catch (Exception e)
            {
                TempData["errorMessage"] = e.Message;
                return View();
            }
        }

        [HttpPost]
        public IActionResult Edit(CityViewModel model)
        {
            string data = JsonConvert.SerializeObject(model);
            StringContent content = new StringContent(data, Encoding.UTF8, "application/json");
            HttpResponseMessage response = _client.PutAsync(_client.BaseAddress + "/City/" + model.Id, content).Result;

            if (response.IsSuccessStatusCode)
            {
                TempData["successMessage"] = "City updated.";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["errorMessage"] = "Some error occured.";
                return View();
            }
        }

        [HttpGet]
        [Route("{id:int}")]
        public IActionResult Delete(int id)
        {
            HttpResponseMessage response = _client.DeleteAsync(_client.BaseAddress + "/city/" + id).Result;

            if (response.IsSuccessStatusCode)
            {
                TempData["successMessage"] = "City deleted.";
                return RedirectToAction("Index");
            }
            else
            {
                TempData["errorMessage"] = "Some error occured.";
                return View();
            }
        }
    }
}

Schools.AspMvc/Controllers/LangController.cs
using Microsoft.AspNetCore.Localization;
using Microsoft.AspNetCore.Mvc;

namespace Schools.MVC.Controllers
{
    public class LanguageController : Controller
    {
        [HttpGet]
        public IActionResult ChangeLanguage()
        {
            string? urlCulture = Request.Query["culture"];
            if (urlCulture != null)
            {
                var culture = new RequestCulture(urlCulture);
                Response.Cookies.Append(
                    CookieRequestCultureProvider.DefaultCookieName,
                    CookieRequestCultureProvider.MakeCookieValue(culture),
                    new CookieOptions { Expires = DateTimeOffset.UtcNow.AddDays(1) }
                );
            }

            string returnUrl = Request.Headers["Referer"].ToString();
            if (string.IsNullOrWhiteSpace(returnUrl))
            {
                returnUrl = "/Home/Index";
            }

            return Redirect(returnUrl);
        }
    }
}

Schools.AspMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Schools.MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Schools.MVC.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Schools.MVC</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="City" asp-action="Index">Cities</a>
                        </li>
                        @if (User.Identity != null && !User.Identity.IsAuthenticated)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
                @if (User.Identity != null && User.Identity.IsAuthenticated)
                {
                    <div>
                        @Html.Label("Welcome: " + User.Identity.Name)
                    </div>
                }
                <ul class="navbar-nav">
                    @if (User.Identity != null && User.Identity.IsAuthenticated)
                    {
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Account" asp-action="Logout">Logout |</a>
                        </li>
                    }
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Language: @Thread.CurrentThread.CurrentUICulture.Name
                        </a>
                        <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                            <li><a asp-controller="Language" asp-action="ChangeLanguage" asp-route-culture="en" class="dropdown-item"> <i class="flag-icon flag-icon-gb"></i> English </a> </li>
                            @* <li><a class="dropdown-item" href="/language/changelanguage?culture=en">En</a></li> *@
                            <li><a class="dropdown-item" href="/language/changelanguage?culture=fr">Fr</a></li>
                        </ul>
                    </li>
                </ul>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @{
                var errorMessage = TempData["errorMessage"]?.ToString();
                var successMassage = TempData["successMessage"]?.ToString();
            }
            @if (!string.IsNullOrWhiteSpace(successMassage))
            {
                <div class="alert alert-success">
                    <b> Success: </b> @successMassage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            else if (!string.IsNullOrWhiteSpace(errorMessage))
            {
                <div class="alert alert-danger">
                    <b> Error: </b> @errorMessage
                    <button type="button" class="btn-close float-end" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            }
            <div>
                @Localizer["home"]
            </div>
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Schools.MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/js/customjs.js"></script>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>